### ISSUE TITLE
external resources

### ISSUE THREAD

**Issue by cjessett** [webdev58/prj-rev-bwfs-dasmoto#1]
(Important) [Here](https://github.com/webdev58/prj-rev-bwfs-dasmoto/blob/98db0b2f7332c2216c950da61fe480b224e5ded2/Dasmotos/index.html#L13) instead of linking to an external resource, include the image in the project and reference it locally. Since URLs can break or change we include all resources with the project.

**Comment by webdev58** [comment]
Will do, thanks.
